# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma

  - repo: local
    hooks:
      - id: black
        name: Format with Black
        entry: poetry run black .
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]

      - id: autoflake
        name: autoflake
        entry: poetry run autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

      - id: pylint
        name: pylint
        entry: poetry run pylint -E app
        language: system
        types: [python]

      - id: flake8
        name: Check with Flake8
        entry: poetry run flake8
        language: system
        pass_filenames: false
        types: [python]
        args: [--count, .]

      - id: yesqa
        name: Remove usless noqa
        entry: poetry run yesqa
        language: system
        types: [python]

      # - id: pytest
      #   name: pytest
      #   entry: poetry run pytest
      #   language: system
      #   pass_filenames: false
      #   types: [python]
