CODE_ERRORS = {
    401: "unauthorized",
    403: "forbidden",
    404: "not-found",
    405: "method-not-allowed",
    422: "validation-error",
    500: "internal-error",
}


NEXXERA_RETURN_MOVEMENT_CODE = {
    "02": "Entrada Confirmada",
    "03": "Entrada Rejeitada",
    "04": "Transferência de Carteira/Entrada",
    "05": "Transferência de Carteira/Baixa",
    "06": "Liquidação",
    "07": "Confirmação do Recebimento da Instrução de Desconto",
    "08": "Confirmação do Recebimento do Cancelamento do Desconto",
    "09": "Baixa",
    "11": "Títulos em Carteira (Em Ser)",
    "12": "Confirmação Recebimento Instrução de Abatimento",
    "13": "Confirmação Recebimento Instrução de Cancelamento Abatimento",
    "14": "Confirmação Recebimento Instrução Alteração de Vencimento",
    "15": "Franco de Pagamento",
    "16": "Abatimento Alterado",
    "17": "Liquidação Após Baixa ou Liquidação Título Não Registrado",
    "18": "Acerto de Depositária (sem motivo)",
    "19": "Confirmação Recebimento Instrução de Protesto",
    "20": "Confirmação Recebimento Instrução de Sustação/Cancelamento de Protesto",
    "21": "Acerto do controle do participante",
    "22": "Título Com Pagamento Cancelado",
    "23": "Remessa a Cartório (Aponte em Cartório)",
    "24": "Retirada de Cartório e Manutenção em Carteira",
    "25": "Protestado e Baixado (Baixa por Ter Sido Protestado)",
    "26": "Instrução Rejeitada",
    "27": "Confirmação do Pedido de Alteração de Outros Dados",
    "28": "Débito de Tarifas/Custas",
    "29": "Ocorrências do Sacado",
    "30": "Alteração de Dados Rejeitada",
    "31": "Cancelamento Abatimento Rejeitado",
    "32": "Estorno de protesto",
    "33": "Confirmação da Alteração dos Dados do Rateio de Crédito",
    "34": "Confirmação do Cancelamento dos Dados do Rateio de Crédito",
    "35": "Confirmação do Desagendamento do Débito Automático",
    "36": "Baixa Rejeitada",
    "37": "Cobrança Contratual - Abatimento e Baixa Bloqueados",
    "38": "Confirmação Recebimento de Instrução de Não Protestar",
    "39": "Alteração do Nome do Sacado",
    "40": "Alteração do Endereço do Sacado",
    "41": "Alteração do Tipo de Cobrança",
    "42": "Débito em conta",
    "43": "Dispensar Juros",
    "44": "Manutenção de título vencido",
    "45": "Conceder desconto",
    "46": "Não conceder desconto",
    "47": "Retificar desconto",
    "48": "Alterar data para desconto",
    "49": "Cobrança de multa",
    "50": "Dispensa de multa",
    "51": "Dispensa de indexador",
    "52": "Dispensa do prazo limite para recebimento do título",
    "53": "Alteração do prazo limite para recebimento do título",
    "54": "Alteração de tipo de cobrança especifico para títulos das carteiras 1 e D",
    "55": "Solicitação encaminhada à Agencia",
    "56": "Crédito no C/C Conta Garantida",
    "57": "Título já Baixado/Liquidado",
    "58": "Título não existe",
    "59": "Cobrança a Creditar",
    "60": "Situação do Título - Cartório",
    "61": "Baixa com crédito direto com valor do crédito informado",
    "62": "Confirmação da alteração do campo seu número",
    "63": "Emissão de Carta de Protesto",
    "64": "Protesto não sustado",
    "65": "Protesto devolvido pelo cartório",
    "66": "Multa alterada",
    "67": "Multa cancelada",
    "68": "Amortização",
    "69": "Baixado e Creditado em Conta Corrente - Adiant Fornecedores",
    "70": "Alteração De Dados - Nova Entrada",
    "71": "Alteração De Dados - Baixa",
    "72": "Baixa Com Transferência Para Desconto",
    "73": "Prazo de Devolução Alterado",
    "74": "Alteração Confirmada",
    "75": "Alteração com Remissão de Bloqueto confirmada",
    "76": "Alteração da Opção de Protesto para devolução Confirmada",
    "77": "Alteração da opção de Devolução para protesto confirmada",
    "78": "Protesto Rejeitado",
    "79": "Abatimento Rejeitado",
    "80": "Instrução Cancelada",
    "81": "Estorno de Sustação de Protesto",
    "82": "Prorrogação vencimento rejeitada",
    "83": "Cancelar protesto rejeitado - Fora de Prazo",
    "84": "Código ocorrência inválido",
    "85": "Estorno de Baixa/Liquidação",
    "86": "Alteração de seu número rejeitada",
    "87": "Não protestar rejeitado",
    "88": "Liquidação parcial efetuada",
    "89": "Liquidação parcial rejeitada",
    "90": "Dispensar juros de mora rejeitado",
    "91": "Uso do banco",
    "92": "Título liquidado no banco correspondente",
    "93": "Título liquidado no cartório do banco correspondente",
    "94": "Baixado creditado diretamente",
    "95": "Uso da Empresa Alterado",
    "96": "Prazo de Protesto Alterado",
    "97": "Alteração de juros de mora",
    "98": "Liquidação Cobrança Garantida S/ Crédito no C/C",
    "99": "Outros",
    "AA": "Transferência Cobrança Garantida para CS",
    "AB": "Título descontado transferido para cobrança simples c/ débito em conta",
    "AC": "Título descontado liquidado com débito em conta",
    "AD": "Alterações específicas da Agencia Bancária - Não Considerar",
    "AE": "Título Sustado Judicialmente",
    "AF": "Transferência de Cedente",
    "AG": "Sustação não acatada",
    "AH": "Juros e Data de Vencimento alterado",
    "AI": "Transferência de Carteira/Desconto",
    "AJ": "Número de Autorização Inexistente",
    "AK": "Título Não Processado",
    "AL": "Alteração de Instrução",
    "AM": "Aguardando Autorização para Protesto por edital",
    "AN": "Protesto Sustado por Alteração de Vencimento e Prazo de Cartório",
    "AO": "Título em Trânsito Pago em Cartório",
    "AP": "Reembolso e Transferência",
    "AQ": "Reembolso e Devolução",
    "AR": "Alteração de Títulos",
    "AS": "Relação de Títulos",
    "AT": "Manutenção Mensal",
    "AU": "Sustação de Cartório e Envio de Título à Cartório",
    "AV": "Fornecimento de formulário pré-impresso",
    "AW": "Estorno Liquidação Parcial",
    "AX": "Devolvido Conforme Instrução",
    "AY": "Devolvido",
    "AZ": "Estorno Devolvido",
    "BA": "Confirmação Invalida",
    "BB": "Pendente para Próxima Fita",
    "BC": "Inconsistência Pendente",
    "BD": "Confirmação de envio de e-mail/SMS",
    "BE": "Envio de e-mail/SMS rejeitado",
    "BF": "Liquidado com Cheque a Compensar",
    "BG": "Instrução Codificada",
    "BH": "Emissão de Segunda Via de Aviso",
    "BI": "Não Conceder Juros Fora do Prazo",
    "BJ": "Protesto Devolvido para Cartório",
    "BK": "Pagamento",
    "BL": "Cobrança Parcial",
    "BM": "Instrução Confirmada",
    "BN": "Entrada Confirmada Com Rateio de Crédito",
    "BO": "Cheque Devolvido",
    "BP": "Baixa por Crédito em C/C sem Título Correspondente",
    "BQ": "Confirmação de Entrada na Cobrança Simples - Entrada Não Aceita na Cobrança Contratual",
    "BR": "Título Para Cobrança em Bancos Correspondentes",
    "BS": "Remessa Já Enviada",
    "BT": "Título Reativado",
    "BU": "Liquidação de Título Vencido",
    "BV": "Título Reclassificado - Título sofreu liquidação reclassificada",
    "BW": "Título Pendente de Qualificação - (Carteira Caução)",
    "BX": "Solicitação de Impressão de Títulos Confirmada",
    "BY": "Confirmação de Inclusão Banco de Sacado",
    "BZ": "Confirmação de Alteração Banco de Sacado",
    "CA": "Confirmação de Exclusão Banco de Sacado",
    "CB": "Emissão de Bloquetos de Banco de Sacado",
    "CC": "Manutenção de Sacado Rejeitada",
    "CD": "Entrada de Título via Banco de Sacado Rejeitada",
    "CE": "Manutenção de banco de Sacado Rejeitada",
    "CF": "Confirmação da Alteração dos Dados do Sacado",
    "CG": "Confirmação da Alteração dos Dados do Sacador/Avalista",
    "CH": "Título Pago com Cheque Devolvido",
    "CI": "Título Pago com Cheque Compensado",
    "CJ": "Instrução para Cancelar Protesto Confirmada",
    "CK": "Instrução para Protesto para Fins falimentares Confirmada",
    "CL": "Confirmação de Instrução de transferência de Carteira/Modalidade de Cobrança",
    "CM": "Alteração de Contrato de Cobrança",
    "CN": "Título DDA Reconhecido Pelo Sacado",
    "CO": "Título DDA Não Reconhecido Pelo Sacado",
    "CP": "Título DDA Recusado Pela CIP",
    "CQ": "Confirmação da Instrução de Baixa de Título Negativado Sem Protesto",
    "CR": "Entrada Registrada Aguardando Avaliação",
    "CS": "Cancelamento do Título",
    "CT": "Confirmação de Pedido de Exclusao de Negativação",
    "CU": "Título enviado para Negativação",
    "CV": "Movimentação na CIP",
    "CW": "Negativação Expressa Informacional",
    "CX": "Confirmação de Entrada em Negativação Expressa/Tarifa",
    "CY": "Confirmação de Cancelamento em Negativação expressa/Tarifa",
    "CZ": "Confirmação Exclusão de Entrada em Negativação Expressa por Liquidação/Tarifa",
    "DA": "Confirmação Recebimento de Instrução de Não Negativar",
    "DB": "Confirmação de Alteração do Valor Nominal do Título",
    "DC": "Título Sustado Judicialmente",
}

MOTIVE_OCCURRENCE_A = {
    "00": "Ocorrência Aceita (ausente de informação)",
    "01": "Código do Banco Inválido",
    "02": "Código do Registro Detalhe Inválido",
    "03": "Código do Segmento Inválido",
    "04": "Código de Movimento Não Permitido para Carteira",
    "05": "Código de Movimento Inválido",
    "06": "Tipo/Número de Inscrição do Cedente Inválidos",
    "07": "Agência/Conta/DV Inválido",
    "08": "Nosso Número Inválido",
    "09": "Nosso Número Duplicado",
    "10": "Carteira Inválida",
    "11": "Forma de Cadastramento do Título Inválido",
    "12": "Tipo de Documento Inválido",
    "13": "Identificação da Emissão do Bloqueto Inválida",
    "14": "Identificação da Distribuição do Bloqueto Inválida",
    "15": "Características da Cobrança Incompatíveis",
    "16": "Data de Vencimento Inválida",
    "17": "Data de Vencimento Anterior a Data de Emissão",
    "18": "Vencimento Fora do Prazo de Operação",
    "19": "Título a Cargo de Bancos Correspondentes com Vencimento Inferior a XX Dias",
    "20": "Valor do Título Inválido",
    "21": "Espécie do Título Inválida",
    "22": "Espécie do Título Não Permitida para a Carteira",
    "23": "Aceite Inválido",
    "24": "Data da Emissão Inválida",
    "25": "Data da Emissão Posterior a Data de Entrada",
    "26": "Código de Juros de Mora Inválido",
    "27": "Valor /Taxa de Juros de Mora Inválido",
    "28": "Código do Desconto Inválido",
    "29": "Valor do Desconto Maior ou Igual ao Valor do Título",
    "30": "Desconto a Conceder Não Confere",
    "31": "Concessão de Desconto - Já Existe Desconto Anterior",
    "32": "Valor do IOF Inválido",
    "33": "Valor do Abatimento Inválido",
    "34": "Valor do Abatimento Maior ou Igual ao Valor do Título",
    "35": "Valor a Conceder Não Confere",
    "36": "Concessão de Abatimento - Já Existe Abatimento Anterior",
    "37": "Código para Protesto Inválido",
    "38": "Prazo para Protesto Inválido",
    "39": "Pedido de Protesto Não Permitido para o Título",
    "40": "Título com Ordem de Protesto Emitida",
    "41": "Pedido de Cancelamento /Sustação para Títulos sem Instrução de Protesto",
    "42": "Código para Baixa/Devolução Inválido",
    "43": "Prazo para Baixa/Devolução Inválido",
    "44": "Código da Moeda Inválido",
    "45": "Nome do Sacado Não Informado",
    "46": "Tipo/Número de Inscrição do Sacado Inválidos",
    "47": "Endereço do Sacado Não Informado",
    "48": "CEP Inválido",
    "49": "CEP Sem Praça de Cobrança (Não Localizado)",
    "50": "CEP Referente a um Banco Correspondente",
    "51": "CEP incompatível com a Unidade da Federação",
    "52": "Unidade da Federação Inválida",
    "53": "Tipo/Número de Inscrição do Sacador/Avalista Inválidos",
    "54": "Sacador/Avalista Não Informado",
    "55": "Nosso número no Banco Correspondente Não Informado",
    "56": "Código do Banco Correspondente Não Informado",
    "57": "Código da Multa Inválido",
    "58": "Data da Multa Inválida",
    "59": "Valor/Percentual da Multa Inválido",
    "60": "Movimento para Título Não Cadastrado",
    "61": "Alteração da Agência Cobradora/DV Inválida",
    "62": "Tipo de Impressão Inválido",
    "63": "Entrada para Título já Cadastrado",
    "64": "Número da Linha Inválido",
    "65": "Código do Banco para Débito Inválido",
    "66": "Agência/Conta/DV para Débito Inválido",
    "67": "Dados para Débito incompatível com a Identificação da Emissão do Bloqueto",
    "68": "Débito Automático Agendado",
    "69": "Débito Não Agendado - Erro nos Dados da Remessa",
    "70": "Débito Não Agendado - Sacado Não Consta do Cadastro de Autorizante",
    "71": "Débito Não Agendado - Cedente Não Autorizado pelo Sacado",
    "72": "Débito Não Agendado - Cedente Não Participa da Modalidade Débito Automático",
    "73": "Débito Não Agendado - Código de Moeda Diferente de Real (R$)",
    "74": "Débito Não Agendado - Data Vencimento Inválida",
    "75": "Débito Não Agendado, Conforme seu Pedido, Título Não Registrado",
    "76": "Débito Não Agendado, Tipo/Num. Inscrição do Debitado, Inválido",
    "77": "Transferência para Desconto Não Permitida para a Carteira do Título",
    "78": "Data Inferior ou Igual ao Vencimento para Débito Automático",
    "79": "Data Juros de Mora Inválido",
    "80": "Data do Desconto Inválida",
    "81": "Tentativas de Débito Esgotado - Baixado",
    "82": "Tentativas de Débito Esgotado - Pendente",
    "83": "Limite Excedido",
    "84": "Número Autorização Inexistente",
    "85": "Título com Pagamento Vinculado",
    "86": "Seu Número Inválido",
    "87": "Código do Movimento não Numérico",
    "88": "Agência do Cedente não prevista",
    "90": "Faixa de aplicação não cadastrada /invalida",
    "91": "Instrução Cancelada",
    "92": "Nome Sacador Avalista invalido ou não informado",
    "93": "Por meio Magnético tele transmissão",
    "94": "Por Via Convencional",
    "95": "Por alteração do código do cedente",
    "96": "Por alteração da variação",
    "97": "Por alteração da carteira",
    "98": "Identificação inválida",
    "99": "Variação da carteira inválida",
    "AA": "Sacado interligado com o sacador",
    "AB": "Título sacado contra órgão do poder publico",
    "AC": "Nome da pessoa autorizada inválido",
    "AD": "Número da prestação do contrato inválido",
    "AE": "Código unidade variável incompatível com o título",
    "AF": "Convênio Inválido",
    "AG": "Título não pertence ao conveniente",
    "AH": "Título com transferência de carteira por prazo superior a XX Dias",
    "AI": "Título não passível de débito/ baixa - situação anormal",
    "AJ": "Transferência de cobrança simples para descontada",
    "AL": "Reembolso de título vendor ou descontado",
    "AM": "Título já liquidado",
    "AN": "Título já baixado",
    "AO": "Título já devolvido",
    "AP": "Número Do borderô inválido",
    "AQ": "Abatimento a cancelar não consta do título.",
    "AR": "Título já se encontra na situação pretendida",
    "AS": "Título fora do prazo admitido para a conta 1",
    "AT": "Título vencido em transferência para carteira 4",
    "AU": "Alteração da situação de débito inválido para cód. Responsabilidade.",
    "AV": "Título com ordem de não protestar -Não pode ser enviado a cartório",
    "AX": "Título /Carne rejeitado.",
    "AZ": "Título não localizado na existência",
    "BA": "Endereço incompleto ou inexistente",
    "BB": "Endereço fora do perímetro urbano",
    "BC": "Endereço não consta do guia da cidade",
    "BD": "Sacado transferiu domicilio",
    "BE": "Sacado não é encontrado no endereço",
    "BF": "Sacado desconhecido",
    "BG": "Sacado alega que não recebeu mercadoria",
    "BH": "Sacado alega que devolveu mercadoria",
    "BI": "Sacado pede dispensa de juros de mora",
    "BJ": "Sacado alega que já pagou ao cadente",
    "BK": "Sacado não reconhece a dívida",
    "BL": "Sacado discorda do valor do título",
    "BM": "Sacado discorda do vencimento",
    "BN": "Sacado em concordata",
    "BO": "Sacado em falência",
    "BP": "Reapresentado",
    "BQ": "Entregue franco de pagamento ao sacado",
    "BR": "Entregue franco de pagamento ao representante",
    "BS": "A entrega franco de pagamento é difícil",
    "BT": "Sacado pede prorrogação",
    "BU": "Sacado pede desconto",
    "BV": "Pedido desconto",
    "BW": "Sacado mudou-se",
    "BX": "Título vencido a mais de 1(um) ano",
    "BY": "Cancelamento de instrução de protesto para título enviado a cartório",
    "BZ": "Portadora indevida para carteira",
    "CA": "Tipo de conta indevido pra carteira",
    "CB": "Instruções de cobrança conflitantes",
    "CC": "Conta cedente inativa - contatar agencia",
    "CD": "Instruções já comandada anteriormente",
    "CE": "Alteração de vencimento não permitida para cobrança",
    "CF": "Tarifa de contratação de título descontado",
    "CG": "Nome do Sacado inválido",
    "CH": "Carteira/Agência/Conta/nosso número inválidos",
    "CI": "Espécie de valor variável invalido",
    "CJ": "Título não selecionado por erro no CNPJ/CPF ou endereço",
    "CK": "Banco aguarda cópia autenticada do documento",
    "CL": "Título rejeitado pelo cartório por estar irregular",
    "CM": "Título não selecionado - praça não atendida",
    "CN": "Cartório aguarda autorização para protestar por edital",
    "CO": "Protesto sustado por solicitação do cedente",
    "CP": "Protesto sustado por alteração no vencimento",
    "CQ": "Aponte cobrado de título sustado",
    "CR": "Protesto sustado por alteração no prazo do protesto",
    "CS": "Entidade Pública",
    "CT": "Título em cartório",
    "CU": "Arquivo em Duplicidade",
    "CV": "Contrato Inexistente",
    "CX": "Título já cadastrado",
    "CZ": "Instrução Invalida",
    "DA": "Valor de desconto exige data limite",
    "DB": "Nome do casado não deve ser informado para nota de seguro",
    "DC": "Número de dias de entrada inválido",
    "DD": "Não existe cotação para moeda na data de emissão",
    "DE": "Banco correspondente não trabalha com moeda fator ou conta não",
    "DF": "Nosso número não reservado para cobrança rápida",
    "DG": "Data de negociação não é dia útil",
    "DH": "Contrato não ligado à cliente",
    "DI": "Contrato não pertence ao cliente do borderô",
    "DJ": "Liquidação /Baixa /Instrução Inibida",
    "DL": "Juros /Multa inválido",
    "DM": "Baixa / Liquidação de título inexistente",
    "DN": "Instrução Prorrogação de vencimento para título liquidado",
    "DO": "Instrução Prorrogação de vencimento para título baixado",
    "DP": "Instrução Prorrogação de vencimento para título protestado",
    "DQ": "Instrução Prorrogação de vencimento para título cartório",
    "DR": "Título não esta em cartório",
    "DS": "Produto não existe no correspondente",
    "DT": "Valor da instrução inválido",
    "DU": "AG. Cobradora inválida",
    "DV": "Abatimento/Alteração Do Valor Do Título Ou Solicitação De Baixa Bloqueada",
    "DX": "Alterações Iguais Para O Mesmo Controle (Agência/Conta/Carteira/Nosso",
    "DZ": "Instrução De Sustar Protesto Rejeitada",
    "EA": "Prêmio Líquido Não Numérico",
    "EB": "Prêmio Líquido Incompatível Com Espécie",
    "EC": "Valores De Descontos Não Numéricos",
    "ED": "Ordem Dos Valores Descontos Incompatíveis",
    "EF": "Percentual Não Permite Valor Abatimento",
    "EG": "Valor Base Exige Data Limite",
    "EH": "Instrução Na Entrada Do Título Inválida",
    "EI": "Valor De Abatimento Entrada Inválido",
    "EJ": "Valor De Abatimento Entr.Tem Que Ser Menor Que Valor Título",
    "EL": "Título Desconto À Vista Ou Contra Apresentação",
    "EM": "Não Existe Cotação Para Moeda Na Data De Emissão",
    "EN": "Data De Negociação Não É Dia Útil",
    "EO": "Espécie Título Para Desconto Func. Alterado Para Np",
    "EP": "Taxa De Desconto Informada Para Borderô De Cobrança/Caução",
    "EQ": "Tipo De Bem (Financiado) Não Cadastrado",
    "ER": "Ressarcimento Invalido",
    "ES": "Uso Da Empresa Obrigatório",
    "ET": "Cálculo Dígito Módulo Não Realizado",
    "EU": "Baixa Crédito Direto Não Permitido Para Desconto",
    "EV": "Processo de Devolução em Andamento",
    "EX": "Movimento Sem Cedente Correspondente",
    "EZ": "Novo Prazo p/ Protesto/ Devolução Inválido",
    "FA": "Título não aceito para compor a carteira de garantias",
    "FB": "Código de ocorrência inválido",
    "FC": "Valor do Desconto inválido",
    "FG": "Título baixado em",
    "FH": "Título Devolvido em",
    "FI": "Concessão de Abatimento inválida",
    "FJ": "Valor em Reais - Mora em moeda",
    "FL": "Tipo Operação inv. p/ seguros c/ IOS",
    "FM": "Tipo de operação inexistente",
    "FN": "Proibido informar número de conta",
    "FO": "Tipo de conta do contrato inexistente",
    "FP": "Mensagem Inválida ou inexistente",
    "FQ": "Título não pode ser baixado",
    "FR": "Falta tipo de conta do Contrato",
    "FS": "Falta Tipo de Pessoa para alterar CGC/CPF",
    "FT": "Depositária Inválida",
    "FU": "Número do Título Inválido",
    "FV": "Valor da comissão de permanência inválido",
    "FW": "Falta Documento do Sacado",
    "FX": "Não cobrável por correspondente",
    "FY": "Taxa Financiamento Inválida",
    "FZ": "Flash Inválido, Registro msg sem flash cadastrado ou flash informado",
    "GA": "Número de Parcela Carnê Inválido",
    "GB": "Intervalo Carnê Inválido",
    "GC": "Erro Quantidade de Alunos Informados",
    "GD": "Nome do Sócio Deve Ser Informado",
    "GE": "Número do Sócio Não Pode Ser Zeros",
    "GF": "CEP do Sócio Não Numérico",
    "GG": "Número do Documento Inválido",
    "GH": "Título Já se Encontra Isento de Juros",
    "GI": "Pago Através de Crédito em C/C e não Baixado",
    "GJ": "Dados do Título Irregulares",
    "GK": "Data da Ocorrência Inválida",
    "GL": "Título não Aceito Para as Carteira Desconto ou Caução",
    "GM": "Título Não Está com Situação “Em Aberto”",
    "GN": "Não Existe Desconto a Ser Cancelado",
    "GO": "Estorno de Envio Não Permitido",
    "GP": "Arquivo Retorno Inexistente para Redisponibilização Nesta Data/Número",
    "GQ": "Cedente Deve Ser Padrão CNB240",
    "GR": "Identificação Banco de Sacado Inválida",
    "GS": "Data Inicial Inválida",
    "GT": "Data Final Inválida",
    "GU": "Banco de Sacado Já Cadastrado",
    "GV": "Cedente Não Cadastrado",
    "GW": "Número de Lote Duplicado",
    "GX": "Opção Para Endosso Inválida",
    "GY": "Preencher Somente Percentual ou Valor",
    "GZ": "Valor Contratual Para Aquisição de Bens Inválido",
    "HA": "Alteração não permitida para carteira de notas de seguros",
    "HB": "Alteração Bloqueada",
    "HC": "Registro em Duplicidade",
    "HD": "Alteração de Vencimento igual a registrada no sistema",
    "HE": "Instrução de Emissão de aviso de cobrança para titulo vencido antes do vencimento",
    "HF": "Solicitação de cancelamento de Instrução Inexistente",
    "HG": "Título sobre alteração de controle",
    "HH": "Solicitação de baixa para título já Baixado ou Liquidado",
    "HI": "Solicitação de Baixa para título em Floating",
    "HJ": "Cancelamento comandado sobre título sem abatimento",
    "HK": "Abatimento / alteração do valor do título ou solicitação de Baixa bloqueados",
    "HL": "Cancelamento comandado sobre título sem desconto",
    "HM": "Título não possui instrução de abatimento",
    "HN": "Controle do participante inválido.",
    "HO": "Flash Inválido, Conta de cobrança com flash cadastrado e sem registro de mensagem correspondente",
    "HP": "Valor do Título faz parte de garantia de empréstimo",
    "HQ": "Uso Exclusivo inválido",
    "HR": "Dados Cheque Não Numéricos",
    "HS": "Sacado não Recadastrado",
    "HT": "Cliente Bloqueado",
    "HU": "Instrução Agendada para Agência",
    "HV": "Cliente não Cadastrado",
    "HW": "Taxa Operação Inválida",
    "HX": "Equalização Inválida",
    "HY": "Taxa Negociável Inválida",
    "HZ": "Operação não Concluída",
    "IA": "Título não Descontado",
    "IB": "Título recusado Como Garantia",
    "IC": "Número de Contrato Inválido",
    "ID": "Título já Reembolsado",
    "IE": "Código Cobrador não Cadastrado",
    "IF": "Sacado Bloqueado",
    "IG": "Destinação automática inválida",
    "IH": "Número do Contrato Inválido",
    "II": "Banco ou Agência Cobradora Inexistente",
    "IJ": "Código Pessoa Inválido",
    "IK": "Falta Numeração - Bloqueto Emitido",
    "IL": "Proibido alterar vencimento de título descontado",
    "IM": "Cobrador Preferencial não Cadastrado",
    "IN": "Solicitação Baixa para título Descontado",
    "IO": "Número do Cheque Duplicado",
    "IP": "Título Baixado por Decurso De Prazo",
    "IQ": "Tarifa/Custas de Protesto",
    "IR": "Tarifa de Sustação",
    "IS": "Código Correspondente Inválido/Duplicado",
    "IT": "Título Pago Com Cheque",
    "IU": "Título Vencido",
    "IV": "Valor de Permanência Inválido",
    "IW": "Remessa de Cobrança Expressa Sendo que a Carteira não é de Cobrança Simples",
    "IX": "Título Zerado ou em Branco, ou não Numérico em Remessa de Cobrança Expressa",
    "IY": "Título Inválido - Cobrança Expressa",
    "IZ": "Título tem Instrução de Cartório Ativa",
    "JA": "Título não tem Instrução de Cartório Ativa",
    "JB": "Título Descontado - Instrução não Permitida Para a Carteira",
    "JC": "Valor de permanência inconsistente, pois dentro de um mês, será maior que o valor do título",
    "JD": "Data de Abatimento Invalida",
    "JE": "Estorno para Título Aberto",
    "JF": "Liquidação Inválida",
    "JG": "e-mail/SMS enviado",
    "JH": "e-mail Lido",
    "JI": "e-mail/SMS devolvido - endereço de e-mail ou número do celular incorreto",
    "JJ": "e-mail devolvido - caixa postal cheia",
    "JK": "e-mail/número do celular do sacado não informado",
    "JL": "Sacado optante por Bloqueto Eletrônico - e-mail não enviado",
    "JM": "Código para emissão de bloqueto não permite envio de e-mail",
    "JN": "Código da Carteira inválido para envio e-mail.",
    "JO": "Contrato não permite o envio de e-mail",
    "JP": "Entradas Rejeitadas - Reprovado no Represamento para Análise",
    "JQ": "Sacado impedido de entrar nesta cobrança",
    "JR": "Título deve estar em aberto e vencido para acatar protesto",
    "JS": "Análise gerencial-sacado inválido p/operação crédito",
    "JT": "Análise gerencial-sacado inadimplente",
    "JU": "Análise gerencial-vencto excede vencto da operação de crédito",
    "JV": "Análise gerencial-sacado com baixa liquidez",
    "JW": "Quantidade de Moeda Inválida",
    "JX": "Análise gerencial-sacado excede concentração",
    "JY": "Título em espera - em análise pelo banco",
    "JZ": "Registro do Sacado Inválido",
    "KA": "Valor Contratual Para Fundo de Reserva Inválido",
    "KB": "Valor de Rendimento de Aplicações Financeiras Inválido",
    "KC": "Valor de Prêmios de Seguros Inválido",
    "KD": "Valor Custas Judiciais Inválido",
    "KE": "Valor de Reembolso de Despesas Inválido",
    "KF": "Valor Outros Inválido",
    "KG": "Valor de Aquisição de Bens Inválidos",
    "KH": "Valor Devolvido ao Consorciado Inválido",
    "KI": "Valor de Despesas de Contrato Inválido",
    "KJ": "Valor de Rendimentos Pagos Inválido",
    "KK": "Data de Descrição Inválida",
    "KL": "Valor do Seguro Inválido",
    "KM": "Data de Nascimento Inválido",
    "KN": "Tipo/Número de Inscrição Do Aluno Inválido",
    "KO": "Data de Avaliação Inválida",
    "KP": "Tipo/Número de Inscrição Do Locatário Inválido",
    "KQ": "Literal de Remessa Inválido",
    "KR": "Tipo de Registro Inválido",
    "KS": "Modelo Inválido",
    "KT": "Código do Banco de Sacados Inválidos",
    "KU": "Banco de Sacados Não Cadastrado",
    "KV": "Não Existem Sacados Para Este Banco",
    "KW": "Preço Unitário do Produto Inválido",
    "KX": "Preço Total do Produto Inválido",
    "KY": "Valor Atual do Bem Inválido",
    "KZ": "Quantidade de Bens Entregues Inválidos",
    "LA": "Título excede prazo máximo de vencimento",
    "LB": "Rejeitado por processo de crédito",
    "LC": "Portfólio destino inexistente",
    "LD": "Alteração inválida (Título caucionado)",
    "LE": "Alteração para título já pago",
    "LF": "Instrução de protesto para título já em cartório",
    "LG": "Alteração para desconto por antecipação inválido",
    "LH": "Prorrogação não permitida",
    "LI": "Instrução de protesto não efetivada por falta de carta de provimento",
    "LJ": "Agencia e Conta não liberada para operar com cobrança",
    "LK": "Quantidade de Bens Distribuídos Inválido",
    "LL": "Quantidade de Bens Não Distribuídos Inválidos",
    "LM": "Número da Próxima Assembléia Inválida",
    "LN": "Horário da Próxima Assembleia Inválido",
    "LO": "Data da Próxima Assembleia Inválida",
    "LP": "Número de Ativos Inválido",
    "LQ": "Número de Desistentes Excluídos Inválido",
    "LR": "Número de Quitados Inválido",
    "LS": "Número de Contemplados Inválido",
    "LT": "Número de Não Contemplados Inválido",
    "LU": "Data da Última Assembleia Inválida",
    "LV": "Quantidade de Prestações Inválida",
    "LW": "Valor da Amortização Inválida",
    "LX": "Código Personalizado Inválido",
    "LY": "Valor da Contribuição Inválido",
    "LZ": "Percentual da Contribuição Inválido",
    "MA": "Valor do Fundo de Reserva Inválido",
    "MB": "Percentual do Fundo de Reserva Inválido",
    "MC": "Prazo Desconto/Multa Preenchido, Obrigatório Percentual ou Valor",
    "MD": "Valor Taxa de Administração Inválida",
    "ME": "Sacado Já Cadastrado (Banco de Sacados)",
    "MF": "Sacado Não Cadastrado (Banco de Sacados)",
    "MG": "Remessa Sem Registro Tipo 9",
    "MH": "Identificação da Solicitação Inválida",
    "MI": "Quantidade Bloquetos Solicitada Inválida",
    "MJ": "Trailer do Arquivo Não Encontrado",
    "MK": "Tipo/Numero de Inscrição do Responsável Inválido",
    "ML": "Código do Modelo Inválido",
    "MM": "Via de Entrega Inválido",
    "MN": "Espécie Banco de Sacado inválido",
    "MO": "Aceite Banco de Sacado Inválido",
    "MP": "Sacado já Cadastrado",
    "MQ": "Sacado Não Cadastrado",
    "MR": "Número do Telefone Inválido",
    "MS": "Tipo/Numero de Inscrição do Condomínio Inválido",
    "MT": "Indicador de Registro de Título Inválido",
    "MU": "Valor da Nota inválido",
    "MV": "Quantidade de Produtos Inválido",
    "MW": "Percentual Taxa de Administração Inválido",
    "MX": "Valor/Percentual de Seguro Inválido",
    "MY": "Valor/Percentual da Diferença da Parcela Inválida",
    "MZ": "Valor/Percentual Reajuste do Saldo de Caixa Inválido",
    "NA": "Valor/Percentual Total a Pagar Inválido",
    "NB": "Valor/Percentual de outros Acréscimos Inválido",
    "NC": "Valor/Percentual de Outras Deduções Inválido",
    "ND": "Valor/percentual da Contribuição Inválido",
    "NE": "Valor/Percentual de Juros/Multa Inválido",
    "NF": "Valor/Percentual Cobrado Inválido",
    "NG": "Valor Disponibilizado em Caixa Inválido",
    "NH": "Valor Depósito Bancário Inválido",
    "NI": "Valor Aplicações Financeiras Inválido",
    "NJ": "Data/Valor Preenchidos, Obrigatório Código Desconto",
    "NK": "Valor Cheque em Cobrança Inválido",
    "NL": "Desconto Com Valor Fixo, Obrigatório Valor do Título",
    "NM": "Data/Hora de Geração Inválida",
    "NN": "Alteração de Dados Inválida",
    "NO": "Apelido do Cliente Não Cadastrado",
    "NP": "Erro na Composição do Arquivo",
    "NQ": "Lote de Serviço Inválido",
    "NR": "Cedente Não Pertence a Cobrança Eletrônica",
    "NS": "Nome da Empresa Inválido",
    "NT": "Nome do Banco Inválido",
    "NU": "Código da Remessa Inválido",
    "NV": "Número de Sequencial de Arquivo Inválido",
    "NW": "Versão do Layout do Arquivo Inválido",
    "NX": "Literal REMESSA-TESTE - Válido só Para Fase Testes",
    "NY": "Literal REMESSA-TESTE - Obrigatório para Fase Testes",
    "NZ": "Tipo de Serviço Inválido",
    "OA": "Forma de Lançamento Inválido",
    "OB": "Número da Remessa Inválido",
    "OC": "Número da Remessa Menor/Igual Remessa Anterior",
    "OD": "Lote de Serviço Divergente",
    "OE": "Número Sequencial de Registro Inválido",
    "OF": "Erro Seqüência de Segmento do Registro Detalhe",
    "OG": "Código Movimento Divergentes entre Grupos de Segmentos",
    "OH": "Quantidade Registro no lote Inválido",
    "OI": "Quantidade Lotes no Arquivo Inválido",
    "OJ": "Quantidade Registro no Arquivo Inválido",
    "OK": "Código DDD Inválido",
    "OL": "Rejeição da Alteração do Prazo Limite de Recebimento",
    "OM": "Rejeição de Dispensa de Prazo Limite de Recebimento",
    "ON": "Rejeição da Alteração do Número de Título Dado Pelo Cedente",
    "OO": "Rejeição da Alteração do Numero Controle do Participante",
    "OP": "Rejeição da Alteração dos Dados do Sacado",
    "OQ": "Rejeição da Alteração dos Dados do Sacador/Avalista",
    "OR": "Sacado DDA",
    "OS": "Título Rejeitado pela checagem de Duplicatas",
    "OT": "Análise gerencial - Entrada de Título Descontado com limite cancelado",
    "OU": "Análise gerencial - Entrada de Título Descontado com limite vencido",
    "OV": "Análise gerencial - cedente com limite cancelado",
    "OX": "Análise gerencial - cedente é sacado e teve seu limite cancelado",
    "OZ": "Análise gerencial - apontamento no Serasa",
    "PA": "Endereço sacador/avalista não informado",
    "PB": "Cep do sacador/avalista não informado",
    "PC": "Cidade do sacador/avalista não informado",
    "PD": "Estado do sacador/avalista inválido ou n informado",
    "PE": "E-mail Sacado não Enviado - Título com Débito Automático",
    "PF": "Sacado Aceita/Reconhece o Faturamento",
    "PG": "E-mail Sacado não Lido no Prazo de 5 dias",
    "PH": "E-mail Sacado não Recebido",
    "PI": "Título Penhorado - Instrução não Liberada Pela Agência",
    "PJ": "Débito Cancelado Pelo Sacado e Mantido Pendente, conforme negociação",
    "PK": "Débito Cancelado Pelo Sacado e Baixado, conforme negociação",
    "PL": "Não Aprovada devido ao impacto da elegibilidade de garantias",
    "PM": "Automaticamente Rejeitada",
    "PN": "Título Pago ou Baixado ou Protestado",
    "PO": "Cancelamento de Valores Inválidos",
    "PP": "Sacado Isento de Protesto e Tentativa de Protesto",
    "PQ": "Entrada rejeitada, Represamento Reprovado",
    "PR": "Instrução rejeitada, Represamento Reprovado",
    "PS": "Valor da Tarifa de Cobrança Inválida",
    "PT": "Título em Pagamento Parcial",
    "PU": "Análise Gerencial - Sacado Difere do Exigido",
    "PV": "Não Foi Possível o Repasse de Tarifas",
    "PW": "Efetivação de Protesto Sem Agenda Válida",
    "PX": "Título não Aceito - Pessoa Física",
    "PY": "Título não Aceito - Por Análise Gerencial",
    "PZ": "Análise Gerencial - Vencimento do Título Abaixo Prazo Curto",
    "QA": "Análise Gerencial - Vencimento do Título Acima Prazo Longo",
    "QB": "Código de Tarifa Inválido Para o Produto",
    "QC": "Código de Tarifa Não Concorda Com o Valor Informado",
    "QD": "Título Já Transferido",
    "QE": "Sacado Não Pode ser Processado Parcealmente",
    "QF": "Título em Prejuízo",
    "QG": "Data de Referência Menor que Data de Emissão do Título",
    "QH": "Nosso Número do Correspondente Não Deve Ser Informado",
    "QI": "Sacador Impedido de Movimentar",
    "QJ": "Serviço e Modalidade Incompatíveis",
    "QK": "Inconsistências Entre Registros Título e Sacador",
    "QL": "Título Com Aceite",
    "QM": "Título em Prejuízo",
    "QN": "Transferido de Protfolio",
    "QO": "Alteração para Título com Instrução de Negativação",
    "QP": "Título Sem Instrução de Negativação",
    "QQ": "Pedido de Negativação Não Aceito Para o Título",
    "QR": "Pedido de Negativação agendado, Sujeito a Análise",
    "QS": "Sacado Não DDA",
    "QT": "Protfólio Destino Inexistente",
    "QU": "Mensagem Não Tratada - Sacado Não é Eletrônico",
    "QV": "Mensagem Não Tratada - Sem Registro Detalhe",
    "QW": "Prazo Inválido Para Negativação",
    "QX": "Estado com Determinação Legal que Impede a Inscrição de Inadimplentes nos Cadastro de Prodeção ao Crédito no Prazo Solicitado",
    "QY": "Valor Nominal do Título Conflitante",
    "QZ": "Tipo de Pagamento Inválido",
    "RA": "Valor Máximo/Percentual Inválido",
    "RB": "Valor Mínimo/Percentual Inválido",
    "RC": "Registro complementar ao cadastro do título da cobrança com e sem registro não cadastrado",
    "RD": "Sacado falecido",
    "RE": "Apresentante não aceita publicação de edital",
    "RF": "Código do Sacado na agência beneficiária está duplicado",
    "ZQ": "Sem informação da nota fiscal eletrônica",
    "ZR": "Chave de acesso NF rejeitada",
    "ZS": "Chave de acesso NF duplicada",
    "ZT": "Quantidade NF excede a quantidade permitida",
    "ZU": "Chave de acesso nota fiscal invalida",
    "P1": "Registrado com QRCODE PIX",
    "P2": "Registrado sem QRCODE PIX",
    "ZZ": "Outros motivos",
}

MOTIVE_OCCURRENCE_B = {
    "00": "Ausente de informação",
    "01": "Tarifa de Extrato de Posição",
    "02": "Tarifa de Manutenção de Título Vencido",
    "03": "Tarifa de Sustação",
    "04": "Tarifa de Protesto",
    "05": "Tarifa de Outras Instruções",
    "06": "Tarifa de Outras Ocorrências",
    "07": "Tarifa de Envio de Duplicata ao Sacado",
    "08": "Custas de Protesto",
    "09": "Custas de Sustação de Protesto",
    "10": "Custas de Cartório Distribuidor",
    "11": "Custas de Edital",
    "12": "Tarifa Sobre Devolução de Título Vencido",
    "13": "Tarifa Sobre Registro Cobrada na Baixa/Liquidação",
    "14": "Tarifa Sobre Reapresentação Automática",
    "15": "Tarifa Sobre Rateio de Crédito",
    "16": "Tarifa Sobre Informações Via Fax",
    "17": "Tarifa Sobre Prorrogação de Vencimento",
    "18": "Tarifa Sobre Alteração de Abatimento/Desconto",
    "19": "Tarifa Sobre Arquivo mensal (Em Ser)",
    "20": "Tarifa Sobre Emissão de Bloqueto Pré-Emitido pelo Banco",
    "80": "Redisponibilização de Arquivo Retorno Eletrônico",
    "81": "Banco de Sacados",
    "82": "Entrega Aviso Disp Bloqueto Via E-mail ao Sacado (s/ Emissão Bloqueto)",
    "83": "Emissão de Bloqueto Pré-impresso Matricial",
    "84": "Emissão de Bloqueto Pré-impresso A4",
    "85": "Emissão de Bloqueto Padrão",
    "86": "Emissão de Bloqueto/Carnê",
    "87": "Emissão de Aviso de Vencido",
    "88": "Alteração Cadastral de Dados do Título - Sem Emissão de Aviso",
    "89": "Emissão de 2a Via de Bloqueto Cobrança Registrada",
    "AA": "Tarifa de Registro",
    "AB": "Tarifa Título Pago no Banco",
    "AC": "Tarifa Título Pago Compensação",
    "AD": "Tarifa Título Baixado Não Pago",
    "AE": "Tarifa Alteração de Vencimento",
    "AF": "Tarifa Concessão de Abatimento",
    "AG": "Tarifa Cancelamento de Abatimento",
    "AH": "Tarifa Concessão de Desconto",
    "AI": "Tarifa Cancelamento Desconto",
    "AJ": "Tarifa Título Pago CICS",
    "AK": "Tarifa Título Pago Internet",
    "AL": "Tarifa Título Pago Term. Gerencial Serviços",
    "AM": "Tarifa Título Pago Pág-Contas",
    "AN": "Tarifa Título Pago Fone Fácil",
    "AO": "Tarifa Título Déb. Postagem",
    "AP": "Tarifa Impressão de Títulos Pendentes",
    "AQ": "Tarifa Título Pago BDN",
    "AR": "Tarifa Título Pago Term. Multi Função",
    "AS": "Impressão de Títulos Baixados",
    "AT": "Impressão de Títulos Pagos",
    "AU": "Tarifa Título Pago Pagfor",
    "AV": "Tarifa Reg/Pgto - Guichê Caixa",
    "AW": "Tarifa Título Pago Retaguarda",
    "AX": "Tarifa Título Pago Subcentro",
    "AY": "Tarifa Título Pago Cartão de Crédito",
    "AZ": "Tarifa Título Pago Comp. Eletrônica",
    "BA": "Tarifa Título Baix. Pg. Cartório",
    "BB": "Tarifa Título Baixado Acerto BCO",
    "BC": "Baixa Registro Em Duplicidade",
    "BD": "Tarifa Título Baixado Decurso Prazo",
    "BE": "Tarifa Título Baixado Judicialmente",
    "BF": "Tarifa Título Baixado Via Remessa",
    "BG": "Tarifa Título Baixado Rastreamento",
    "BH": "Tarifa Título Baixado Conf. Pedido",
    "BI": "Tarifa Título Baixado Protestado",
    "BJ": "Tarifa Título Baixado Para Devolução",
    "BK": "Tarifa Título Baixado Franco Pagto",
    "BL": "Tarifa Título Baixado SUST/ RET/ CARTÓRIO",
    "BM": "Tarifa Título Baixado SUS/ SEM/ REM/ CARTÓRIO",
    "BN": "Tarifa Título Transferido Desconto",
    "BO": "Cobrado Baixa Manual",
    "BP": "Baixa Por Acerto Cliente",
    "BR": "Tarifa Baixa Por Contabilidade",
    "BS": "Tr. Tentativa Cons. Déb. Aut.",
    "BT": "Tr. Crédito Online",
    "BU": "Tarifa Reg/ Pagto Bradesco Expresso",
    "BV": "Tarifa Emissão Papeleta",
    "BW": "Tarifa Fornec. Papeleta Semi Preenchida",
    "BX": "Acondicionador de Papeletas (RPB)S",
    "BY": "Acond. De Papeletas (RPB)S PERSONAL",
    "BZ": "Papeleta Formulário Branco",
    "CA": "Formulário A4 Serrilhado",
    "CB": "Fornecimento de Softwares Transmiss.",
    "CC": "Fornecimento de Softwares Consulta",
    "CD": "Fornecimento Micro Completo",
    "CE": "Fornecimento MODEN",
    "CF": "Fornecimento de Máquina FAX",
    "CG": "Fornecimento de Máquinas Óticas",
    "CH": "Fornecimento de Impressoras",
    "CI": "Reativação de Título",
    "CJ": "Alteração de Produto Negociado",
    "CK": "Tarifa Emissão de Contra Recibo",
    "CL": "Tarifa Emissão 2a via Papeleta",
    "CM": "Tarifa Regravação Arquivo Retorno",
    "CN": "Arq. Títulos a Vencer Mensal",
    "CO": "Listagem Auxiliar de Crédito",
    "CP": "Tarifa Cadastro Cartela Instrução Permanente",
    "CQ": "Canalização de Crédito",
    "CR": "Cadastro de Mensagem Fixa",
    "CS": "Tarifa Reapresentação Automática Título",
    "CT": "Tarifa Registro Título Déb. Automático",
    "CU": "Tarifa Rateio de Crédito",
    "CV": "Emissão Papeleta Sem Valor",
    "CW": "Sem Uso",
    "CX": "Cadastro de Reembolso de Diferença",
    "CY": "Relatório Fluxo de Pagto",
    "CZ": "Emissão Extrato Mov. Carteira",
    "DA": "Mensagem Campo Local de Pagto",
    "DB": "Cadastro Concessionária Serv. Públ.",
    "DC": "Classif. Extrato Conta Corrente",
    "DD": "Contabilidade Especial",
    "DE": "Realimentação Pagto",
    "DF": "Repasse de Créditos",
    "DG": "Tarifa Reg. Pagto Banco Postal",
    "DH": "Tarifa Reg. Pagto Outras Mídias",
    "DI": "Tarifa Reg/Pagto - Net Empresa",
    "DJ": "Tarifa Título Pago Vencido",
    "DK": "TR Tít. Baixado Por Decurso Prazo",
    "DL": "Arquivo Retorno Antecipado",
    "DM": "Arq. Retorno Hora/Hora",
    "DN": "TR. Agendamento Déb. Aut.",
    "DO": "TR. Agendamento Rat. Crédito",
    "DP": "TR Emissão Aviso Rateio",
    "DQ": "Extrato de Protesto",
    "DR": "Tarifa Sobre Instruções - Mês Anterior",
    "DS": "Tarifa Sobre Baixas - Mês Anterior",
    "DT": "Tarifa Sobre Entradas - Mês Anterior",
    "DU": "Tarifa Sobre Instruções de Protesto/Sustação - Mês Anterior",
}

MOTIVE_OCCURRENCE_C_06 = {
    "00": "Ausente de informação",
    "01": "Por Saldo",
    "02": "Por Conta",
    "03": "No Próprio Banco",
    "04": "Compensação Eletrônica",
    "05": "Compensação Convencional",
    "06": "Por Meio Eletrônico",
    "07": "Após Feriado Local",
    "08": "Em Cartório",
    "16": "Em Dinheiro",
    "17": "Em Cheque",
    "20": "Por Débito em Conta",
    "21": "Normal",
    "22": "Sem Registro",
    "23": "Na apresentação",
    "30": "Liquidado no Banco em Cheque",
    "31": "Liquidado em banco Correspondente",
    "35": "Liquidado - baixado /devolvido em data anterior dinheiro",
    "36": "Liquidado - baixado /devolvido em data anterior cheque",
    "37": "Lotérica",
    "38": "Outros canais",
    "39": "Correspondente Bancário",
    "41": "Agendamento - Pagamento Agendado Via Sistema Ou Outro Canal Eletrônico e Liquidado na data indicada",
    "75": "Liquidado por Meio de Central de Atendimento (Telefone)",
    "76": "Liquidado Correspondente em Dinheiro",
    "77": "Liquidado Correspondente em Cheque",
    "78": "Liquidado Office Banking",
    "79": "Liquidação na Internet (Home Banking)",
    "80": "Caixa Eletrônico",
    "81": "Itaú BankFone",
    "82": "Itaú BankLine",
    "83": "Recebimento OFF-Line",
    "84": "Pelo Código de Barras",
    "85": "Pela Linha Digitável",
    "86": "Pelo Auto Atendimento",
    "87": "Sistema de Contas a pagar Itaú",
    "88": "Por Débito em Conta, Dinheiro ou Cheque do Próprio Banco",
    "89": "Capturado em OFF-Line no Próprio Banco",
    "90": "Pagamento em Cartório com Cheque",
    "91": "Rateio Não Efetuado",
    "92": "Liquidação Interbancária",
    "93": "Liquidação Parcial",
    "94": "Pago com cheque - bloqueado 24 horas",
    "95": "Pago com cheque - bloqueado 48 horas",
    "96": "Pago com cheque - bloqueado 72 horas",
    "97": "Pago com cheque - bloqueado 96 horas",
    "98": "Pago com cheque - bloqueado 120 horas",
    "99": "Pago com cheque - bloqueado 144 horas",
}

MOTIVE_OCCURRENCE_C_09 = {
    "00": "Ausente de Informação",
    "09": "Comandada Banco",
    "10": "Comandada Cliente Arquivo",
    "11": "Comandada Cliente On-line",
    "12": "Decurso Prazo - Cliente",
    "13": "Decurso Prazo - Banco",
    "14": "Protestado",
    "15": "Título Excluído",
    "18": "Título baixado e transferido para desconto",
    "19": "Baixando conforme instrução da Agência",
    "24": "Por Alteração da Carteira",
    "25": "Débito Automático",
    "26": "Baixa por Pagamento",
    "27": "Liquidado Anteriormente",
    "28": "Habilitado em processo",
    "29": "Incobrável por nosso intermédio",
    "30": "Transferido para crédito em liquidação",
    "32": "Por alteração da variação",
    "33": "Acerto",
    "34": "Automático",
    "40": "Telefone",
    "42": "Por alteração do código do cedente",
}
