name: bankslipanalyzer - Linting & Test

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - 'bank_return/**'
      - 'bank_shipping/**'
      - 'bank_slip/**'
    branches:
      - main
  pull_request:
    paths:
      - 'app/**'
      - 'bank_return/**'
      - 'bank_shipping/**'
      - 'bank_slip/**'
    branches:
      - main

jobs:
  linting:
    uses: ./.github/workflows/python-linting.yml
    with:
      project: app
  deploy:
    needs: linting
    uses: ./.github/workflows/deploy-fly.yml
    secrets: inherit
