name: bankslipanalyzer - Linting & Test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths:
      - app/**"
  pull_request:
    paths:
      - app/**"
    branches:
      - develop
      - main

jobs:
  linting:
    uses: ./.github/workflows/python-linting.yml
    with:
      project: app
  # testing:
  #   uses: ./.github/workflows/python-testing.yml
  #   with:
  #     project: bills-to-pay
  # ci:
  #   uses: ./.github/workflows/ci.yml
  #   with:
  #     project: bills-to-pay
